# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# https://developer.android.com/studio/command-line for more details.
# For more details on building Android apps, read the Security with Gradle documentation at
# https://developer.android.com/studio/build/security-and-performance.

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does nothing when the
# generated R class is empty. More details at https://developer.android.com/studio/build/namespacing
android.useNamespace=true

# Kotlin
kotlin.code.style=official

# JVM
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m

# Build features
android.enableJetifier=true
